dataset_name: bcic2a_loso
max_epochs: 1000
model: lstm
model_kwargs:
  dropout: 0.25
  hidden_size: 16
  label_smoothing: 0.1
  lr: 0.005
  lstm_size: 32
  n_channels: 22
  n_classes: 4
  optimizer: adam
  scheduler: false
  warmup_epochs: 50
  weight_decay: 0.001
preprocessing:
  alignment: riemann
  batch_size: 64
  high_cut: 40
  low_cut: 0
  sfreq: 250
  start: 0.0
  stop: 0.0
seed: 0
subject_ids: all
train_individual: false
