# general
dataset_name: "bcic2a_loso"
subject_ids: "all"  # either "all" or integer
max_epochs: 1000
seed: 0
train_individual: false

# preprocessing
preprocessing:
  sfreq: 250
  low_cut: 0
  high_cut: 40
  start: 0.0
  stop: 0.0
  alignment: "riemann"
  batch_size: 64

# model
model: "lstm"
model_kwargs:
  n_channels: 22
  lstm_size: 32
  hidden_size: 16
  n_classes: 4
  dropout: 0.25
  lr: 0.005
  weight_decay: 0.001
  optimizer: "adam"
  scheduler: false
  warmup_epochs: 50
  label_smoothing: 0.1
