source_run: "src-bcic2a_loso_2023-12-04_14-40-57"
tta_method: "energy_adaptation"
continual: false
tta_config:
  alignment: False # [False, "euclidean", "riemann"]
  averaging_method: "ema"  # ["equal", "linear", "ema"]
  align_alpha: 0.1
  buffer_length: 32
  optimizer: "Adam"
  optimizer_kwargs:
    lr: 0.0005
    beta: 0.9
    weight_decay: 0.0
  log_name: "energy-pink_noise"
