source_run: "src-bcic2a_loso_2023-12-04_14-41-13"
tta_method: "energy_adaptation"
continual: false
tta_config:
  alignment: False #"riemann" # [False, "euclidean", "riemann"]
  averaging_method: "ema"  # ["equal", "linear", "ema"]
  align_alpha: 0.1
  buffer_length: 32
  langevin_init:
    series_length: 1000
    # kernel: "rbf"
    # length: 2
    # scale: 0.03
  optimizer: "Adam"
  optimizer_kwargs:
    lr: 0.005
    beta: 0.9
    weight_decay: 0.0
