source_run: "src-bcic2b_within_2023-12-04_18-31-55"
tta_method: "entropy_minimization"
continual: false
tta_config:
  alignment: False # [False, "euclidean", "riemann"]
  averaging_method: "ema"  # ["equal", "linear", "ema"]
  align_alpha: 0.1
  buffer_length: 32
  optimizer: "Adam"
  optimizer_kwargs:
    lr: 0.0005
    beta: 0.9
    weight_decay: 0.0
  log_name: "entropy_min_corrupt-b-sev-5"