source_run: "src-bcic2a_loso_2025-05-21_15-52-09"
tta_method: "entropy_minimization"
continual: false
tta_config:
  alignment: "riemann" # [False, "euclidean", "riemann"]
  averaging_method: "ema"  # ["equal", "linear", "ema"]
  align_alpha: 0.1
  buffer_length: 32
  optimizer: "Adam"
  optimizer_kwargs:
    lr: 0.0005
    beta: 0.9
    weight_decay: 0.0
  log_name: "subject_1-entropy"
  train_bn_only: False
